name: CI-CD-pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test
      - name: Run Additional Tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  # Deploy Preview Job
  deploy-preview:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Set up Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Commit and Push to Preview Branch
        run: |
          git config --local http.extraHeader "Authorization: basic $(echo -n x-access-token:${{ secrets.MY_REPO_TOKEN }} | base64)"
          git checkout -b preview
          git add ./dist -f
          git commit -m "Deploying preview to 'preview' branch"
          git push origin preview --force
        env:
          MY_TOKEN: ${{ secrets.MY_REPO_TOKEN }}
        

  # Deploy Production Job
  deploy-production:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
