name: Deploy to Vercel Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    branches:
      - feat-reload-pwa

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or any other version you prefer

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Assuming this command builds your project into ./dist

      - name: Push to preview branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b preview
          git add dist -f
          git commit -m "Deploy to preview branch"
          git push origin preview --force

  deploy-to-vercel:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'preview' # Checkout the preview branch

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy preview + assign beta domain
        run: |
          OUTPUT=$(du --inodes -d 5 .vercel/output)
          echo "$OUTPUT"
          LAST=$(echo "$OUTPUT" | tail -n 1)
          PERCENTAGE=$(echo "$LAST" | awk 'BEGIN {maxtotal=15000} { printf "%.2f%%", ($1/maxtotal*100) }')
          echo "Vercel file usage percentage" >> $GITHUB_STEP_SUMMARY
          echo "$PERCENTAGE" >> $GITHUB_STEP_SUMMARY
          du -h -d 3 .vercel/output/functions/en
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          vercel alias --scope ${{ secrets.VERCEL_TEAM_ID }} --token ${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` ssync-preview.vercel.app
